name: chips_input_autocomplete
description: "Flutter package to create a chips input with autocomplete."
version: 1.0.1+2
homepage:
repository: https://github.com/BruckCode/chips_input_autocomplete
issue_tracker: https://github.com/BruckCode/chips_input_autocomplete/issues

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

screenshots:
  - description: 'Default Example of the chips input autocomplete.'
    path: demo_basic.webp
  - description: 'Example of the chips input autocomplete with add on selection.'
    path: demo_add_on_selection.webp
  - description: 'Example of the chips input autocomplete with only options allowed.'
    path: demo_only_options_allowed.webp
  - description: 'Example of the chips input autocomplete with async options fetched.'
    path: demo_async_fetched.webp

flutter: