name: chips_input_autocomplete
description: "Flutter package to create a chips input with autocomplete."
version: 0.1.0
homepage:
repository: https://github.com/BruckCode/chips_input_autocomplete
issue_tracker: https://github.com/BruckCode/chips_input_autocomplete/issues

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: